apiVersion: v2
type: application
appVersion: latest
description: A Matrix-Signal puppeting bridge.
name: mautrix-signal
version: 0.1.0
keywords:
  - synapse
  - chat
  - matrix
  - signal
home: https://github.com/tulir/mautrix-signal
sources:
  - https://github.com/matrix-org/synapse
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - both signald and mautrix-signal are using user 1337 now
    - update to latest signald
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: mautrix-signal
      image: dock.mau.dev/mautrix/signal:latest
    - name: signald
      image: signald/signald:0.18.2
