apiVersion: apps/v1
{{- $podAnnotations := .Values.podAnnotations }}
{{- $secretAnnotation := dict "checksum/secret" (include (print $.Template.BasePath "/secrets.yaml") . | sha256sum) }}
{{- $podAnnotations := merge $podAnnotations $secretAnnotation }}
kind: Deployment
metadata:
  name: {{ include "mautrix-signal.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mautrix-signal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
    {{- if eq .Values.strategy.type "Recreate" }}
    rollingUpdate: null
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mautrix-signal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mautrix-signal.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "mautrix-signal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init
          image: "{{ .Values.image.mautrixSignal.registry }}/{{ .Values.image.mautrixSignal.repository }}:{{ .Values.image.mautrixSignal.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.mautrixSignal.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |-
              set -ex
              cp /config/*.yaml /data/
              mkdir -p "{{.Values.config.signal.outgoing_attachment_dir }}"
              chown -R 1337:1337 /signald
              chown -R 1337:1337 /data
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: signald
              mountPath: /signald
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: mautrix-signal
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.mautrixSignal.registry }}/{{ .Values.image.mautrixSignal.repository }}:{{ .Values.image.mautrixSignal.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.mautrixSignal.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ required "need config.appservice.port" .Values.config.appservice.port }}
              protocol: TCP
          {{- with .Values.probes.liveness }}
          livenessProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
            failureThreshold: {{ .failureThreshold }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
            failureThreshold: {{ .failureThreshold }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
          {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
          {{- with .Values.probes.startup }}
          startupProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds }}
            failureThreshold: {{ .failureThreshold }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: signald
              mountPath: /signald
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: signald
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.signald.registry }}/{{ .Values.image.signald.repository }}:{{ .Values.image.signald.tag }}"
          imagePullPolicy: {{ .Values.image.signald.pullPolicy }}
          args:
            # user socket
            - -s
            - "/signald/signald.sock"
            # where data is stored
            - -d
            - "/signald"
            # enable metrics
            - -m
            # metrics port
            - --metrics-http-port=9595
          ports:
            - name: http
              containerPort: {{ required "need config.appservice.port" .Values.config.appservice.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: signald
              mountPath: /signald
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "mautrix-signal.fullname" . }}
        - name: data
          emptyDir: {}
        - name: signald
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "mautrix-signal.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
