{{- if .Values.config }}
{{- if .Values.config.appservice }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautrix-signal.fullname" . }}
  labels:
{{ include "mautrix-signal.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ required "need config.appservice.port" .Values.config.appservice.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.config.metrics.enabled }}
    - port: {{ .Values.config.metrics.listen_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "mautrix-signal.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
